{{- if (.Values.flagger.enabled) }}
apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: {{ include "service-deployment.fullname" . }}
  labels:
    {{- include "service-deployment.labels" . | nindent 4 }}
spec:
  provider: {{ .Values.flagger.provider | default "nginx" }}
  # deployment reference
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "service-deployment.fullname" . }}
  # ingress reference (Flagger will create a canary ingress based on this)
  ingressRef:
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    name: {{ include "service-deployment.fullname" . }}-{{ .Release.Namespace }}-internal
  # the maximum time in seconds for the canary deployment
  # to make progress before it is rollback (default 600s)
  progressDeadlineSeconds: {{ .Values.flagger.progressDeadlineSeconds }}
  # HPA reference (optional)
  {{- if .Values.hpa.enabled }}
  autoscalerRef:
    {{- if eq .Values.hpa.memory.target "Utilization" }}
    apiVersion: autoscaling/v2
    {{- else }}
    apiVersion: autoscaling/v2beta2
    {{- end }}
    kind: HorizontalPodAutoscaler
    name: {{ include "service-deployment.fullname" . }}
  {{- end }}
  service:
    # ClusterIP service port number
    port: 80
    # container port number or name
    targetPort: app-port
  analysis:
    # schedule interval (default 60s)
    interval: {{ .Values.flagger.interval }}
    # max number of failed metric checks before rollback
    threshold: {{ .Values.flagger.threshold }}
    {{- if hasKey .Values.flagger "skipAnalysis" }}
    # deploy straight to production without the metrics and webhook checks
    skipAnalysis: {{ .Values.flagger.skipAnalysis }}
    {{- end }}
    # max traffic percentage routed to canary
    # percentage (0-100)
    {{- if or (eq .Values.flagger.type "canary") (not .Values.flagger.type) }}
    maxWeight: {{ .Values.flagger.maxWeight }}
    # canary increment step
    # percentage (0-100)
    stepWeight: {{ .Values.flagger.stepWeight }}
    {{- else if eq .Values.flagger.type "bluegreen" }}
    iterations : {{ .Values.flagger.iterations }}
    {{- end }}
    {{- if .Values.flagger.metrics }}
    metrics:
    {{- range $value := $.Values.flagger.metrics }}
    - name: {{ $value.name }}
      thresholdRange:
        {{- if $value.thresholdRange.min }}
        min: {{ $value.thresholdRange.min }}
        {{- end }}
        {{- if $value.thresholdRange.max }}
        max: {{ $value.thresholdRange.max }}
        {{- end }}
      interval: {{ $value.interval }}
      {{- if $value.templateRef }}
      templateRef:
        name: {{ $value.templateRef.name }}
        {{- if $value.templateRef.namespace }}
        namespace: {{ $value.templateRef.namespace }}
        {{- end }}
      {{- end }}
    {{- end }}
    {{- end }}
    {{- if .Values.flagger.webhooks }}
    webhooks:
    {{- range $hook := $.Values.flagger.webhooks }}
    - name: {{ $hook.name }}
      {{- if $hook.type }}
      type: {{ $hook.type }}
      {{- end }}
      url: {{ $hook.url }}
      {{- if $hook.timeout }}
      timeout: {{ $hook.timeout }}
      {{- end }}
      {{- if $hook.metadata }}
      metadata:
        {{- toYaml $hook.metadata | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- end }}
---
{{- end }}
